name: GOOGLE

on:
  workflow_dispatch:

permissions: read-all

jobs:
  google:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: google-github-actions/auth@v2
        with:
          export_environment_variables: true
          service_account: github-runner@hc-e95fbb5cfc36456086463eaf02a.iam.gserviceaccount.com
          workload_identity_provider: projects/896622764/locations/global/workloadIdentityPools/github/providers/github
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.0
      - name: Initialize
        run: terraform init
      - name: Run Tests
        run: terraform test
